import { Poppins } from "next/font/google"
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css"
import { ModeToggler } from "@/components/mode-toggler"
import Nabar from "@/components/navbar"
import { cn } from "@/lib/utils"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(poppins.className, "min-h-screen w-full")}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Nabar />
          <main className="mt-[20px]">{children}</main>
          <ModeToggler />
        </ThemeProvider>
      </body>
    </html>
  )
}
